from django.urls import path, include
from rest_framework.routers import DefaultRouter

from myrecipe import views

"""
    A Default router is a feature of the Django rest framework
    that will automatically generate the urls for our user.
    /api/recipe/tags/1/  /api/recipe/tags/1/user... etc
    this router automatically registers the apropiate urls
    for all of the actions in our user.
"""
router = DefaultRouter()
# Registers our viewset with our router
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)
"""
    All of the urls that are generated by our default router
    will now be included in the url patterns and if we add
    anymore viewsets, we can just register them here
"""

app_name = 'recipe'

urlpatterns = [
    path('', include(router.urls))
]
